import model
import csv
from datetime import datetime

def load_users(session):
    # use u.user
    with open('seed_data/u.user', 'rb') as file:
        reader = csv.reader(file, delimiter= '|')    # reader function takes each line of the file & makes a list containing all that line's columns
        for row in reader:
            age = row[1]
            zipcode = row[4]
            u = model.User(email=None, password=None, age=age, zipcode=zipcode)       # don't pass in id bc it was autogenerated by SQLAlchemy (bc it is a primary key)
            session.add(u)
    session.commit()

def load_movies(session):
    # use u.item
    with open('seed_data/u.item', 'rb') as file:
        reader = csv.reader(file, delimiter = '|')
        for row in reader:
            title = row[1].decode("latin-1")
            if row[2] != "":
                rel_date = datetime.strptime(row[2], "%d-%b-%Y")
            else:
                rel_date = None
            url= row[4]
            m = model.Movie(title=title, rel_date=rel_date, url=url)
            session.add(m)
    session.commit()

def load_ratings(session):
    # use u.data
    with open('seed_data/u.data', 'rb') as file:
        reader = csv.reader(file, delimiter = '\t')
        for row in reader:
            rating = row[2]
            user_id = row[0]
            movie_id = row[1]
            r = model.Rating(user_id=user_id,movie_id=movie_id,rating=rating)
            session.add(r)
    session.commit()

def main(session):
    # You'll call each of the load_* functions with the session as an argument
    load_movies(session)
    load_users(session)
    load_ratings(session)

if __name__ == "__main__":
    # s= model.connect()
    s = model.session
    main(s)
